### ISSUE TITLE
Help please. Does not compile against latest source of crdroid 13/14

### ISSUE THREAD

**Issue by Ziggy815** [crdroidandroid/android_device_xiaomi_topaz#4]
Hi there,

i tried to compile this device under 13/14 with a fresh synced source.
Its not possible to compile with this device source.
There are many deps missing. Please add depency file and kernel. 

I thought official devices would compile without problems but here seems much missing.

Help would be highly appreciated

Greetings
Zig.

**Comment by gwolf2u** [comment]
this dt doesn't use crdroid.dependencies, feature we don't enforce, so won't compile directly
close manually all needed dt stuff
