### ISSUE TITLE
Please fix build errors

### ISSUE THREAD

**Issue by Dusty815** [crdroidandroid/android_device_xiaomi_topaz#5]
@mirabelle1999

Hi,

please be so kind and check after you uploaded a device tree if it has the chance to build.

For compiling you need at least to change the wrong filenames like aosp_topaz.mk along with the wrong pointers in AndroidProducts.mk
to lineage_topaz.mk.

Also $(call inherit-product, vendor/aosp/config/common_full_phone.mk) in lineage_topaz.mk will not work in  crDroid.

Now its at least compiling. Can tell you later if it works.

Please dont get me wrong i am happy and thankfull that someone is developing for this device, but please make sure that you upload the correct source, specialy when it shall be official.

Best regards and no offence :)

Update : There are also dupes in overlay/TopazFrameworksOverlay/res/values/config.xml that prevents compiling.

**Comment by mirabelle1999** [comment]
Hello there. I'm still rebasing my trees right now. ill update it once I'm done.

**Comment by mirabelle1999** [comment]
I already update the trees. but it's not yet completed. ill update it again once I'm not busy or I have time

**Comment by Dusty815** [comment]
Thanks very much for the Info! I will keep and eye on it and give it another try next weekend :)
